<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLb5ESNm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLb5ESNm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLb5ESNm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLb5ESNm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLb5ESNm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lb5ESNm',
    'container.build_id' => '86cd416a',
    'container.build_time' => 1596630245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLb5ESNm');
