<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSAXUDra\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSAXUDra/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSAXUDra.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSAXUDra\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSAXUDra\App_KernelDevDebugContainer([
    'container.build_hash' => 'SAXUDra',
    'container.build_id' => 'b736e202',
    'container.build_time' => 1595521788,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSAXUDra');
