<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAGIh3l5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAGIh3l5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAGIh3l5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAGIh3l5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAGIh3l5\App_KernelDevDebugContainer([
    'container.build_hash' => 'AGIh3l5',
    'container.build_id' => 'cd781fb0',
    'container.build_time' => 1593538528,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAGIh3l5');
